apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-node-b-pvc
  namespace: overlay-network
spec:
  storageClassName: ipfs-node-b-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi