apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-node-a-pv
spec:
  storageClassName: data-node-a-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/node-a"