apiVersion: v1
kind: Pod
metadata:
  name: ipfs-node-a
  namespace: overlay-network
  labels:
    node: ipfs-node-a
spec:
  volumes:
    - name: ipfs-storage
      persistentVolumeClaim:
        claimName: ipfs-node-a-pvc
  containers:
    - name: kubo
      image: ipfs/kubo:master-latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/data/ipfs"
          name: ipfs-storage