apiVersion: v1
kind: Pod
metadata:
  name: ipfs-node-b
  namespace: overlay-network
  labels:
    node: ipfs-node-b
spec:
  volumes:
    - name: data-path
      persistentVolumeClaim:
        claimName: data-node-b-pvc
  containers:
    - name: kubo
      image: ipfs/kubo:master-latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/data/ipfs"
          name: data-path