apiVersion: v1
kind: Service
metadata:
  name: ipfs-node-b-service
  namespace: overlay-network
  labels:
    node: ipfs-node-b-service
spec:
  type: LoadBalancer
  ports:
    - name: "swarm"
      port: 4001
    - name: "api"
      port: 5001
    - name: "gateway"
      port: 8080
  selector:
    node: ipfs-node-b